name: plain project 배포

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: repository 확인
        uses: actions/checkout@v3

      - name: Docker image build 및 push
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u kimsee --password-stdin
          docker build -t kimsee/plain:latest ./Plain
          docker images
          docker push kimsee/plain:latest

      - name: SSH로 EC2에 로그인 후 배포포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/Testback/Plain  # docker-compose3.yaml이 위치한 폴더로 이동
            docker-compose pull  # 최신 이미지 가져오기
            docker compose -f docker-compose3.yaml up -d  #docker compose 실행

